nama=("AZKA IBAD")
nim=("TI20230006")
semester=("2(dua)")
status=("Pelajar (Mahasiswa)")
agama=("ISLAM")
lahir=("MATARAM,04 JANURAI 2005")
usia=int(19)
kelamin=("LAKI - LAKI")
alamat=("Dusun Kesambik Ngelah Desa Beraim kec.praya tengah")
email=("kaibad611@gmial.com")
wa=("+6287847512769")
fb=("Ka Ibad")
ig=("_azka_xyx")
tiktok=("azka09990")
sd=("SDN 3 BERAIM")
smp=("MTs AL-HASANAIN NU BERAIM")
sma=("SMK AL-HASANAIN NU BERAIM")
kuliah=("SEKOLAH TINGGI MANAJEMEN INFORMASI DAN KOMUNIKASI LOMBOK")
pengalaman1=("Magang di NOVOTEL LOMBOK (hotel and risort)")
pengalaman2=("Kerja sebagai kasir di kantin")  
pengalaman3=("Jualan es di depan rumah")
keahlian=("Publik Spiking lumayan bagus")


print("--------------------------------------")
print("         CURRICULUM VITAE             ")
print("by : azka ibad")
print("--------------------------------------")
print("")
print("DATA PRIBADI")
print("--------------------------------------")
print("|    Nama                   | ",nama)
print("|    Status                 | ",status)
print("|    NIM                    | ",nim)
print("|    Semester               | ",semester)
print("|    Jenis Kelamin          | ",kelamin)
print("|    Agama                  | ",agama)
print("|    Tempat & Tanggal Lahir | ",lahir)
print("|    Umur                   | ",usia,"Tahun")
print("|    Alamat                 | ",alamat)
print("--------------------------------------")
print("")
print("PENDIDIKAN")
print("--------------------------------------")
print("SEKOLAH DASAR             | ",sd)
print("SEKOLAH MENENGAH PERTAMA  | ",smp)
print("SEKOLAH MENENGAH KEJURUAN | ",sma)
print("PERGURUAN TINGGI          | ",kuliah)
print("--------------------------------------")
print("")
print("MEDIA SOSIAL")
print("--------------------------------------")
print("|    NOMOR HP/WA | ",wa)
print("|    INSTAGRAM   | ",ig)
print("|    FACEBOOK    | ",fb)
print("|    TIKTOK      | ",tiktok)
print("|    E_mail      | ",email)
print("--------------------------------------")
print("")
print("PENGALAMAN")
print("--------------------------------------")
print("- ",pengalaman1)
print("- ",pengalaman2)
print("- ",pengalaman3)
print("--------------------------------------")
print("")
print("KEAHLIAN")
print("--------------------------------------")
print("- ",keahlian)
print("--------------------------------------")
print("            TERIMA KASIH              ")
print("--------------------------------------")